name: 'Delete non-friends record'

on:
  # è¿›è¡Œæ‰‹åŠ¨æ§åˆ¶
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: 'ä¸‹è½½æºç ğŸ—ï¸'
        uses: actions/checkout@v4
      - name: 'è®¾ç½®Pythonç¯å¢ƒğŸ”„ï¸'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'å®‰è£…ä¾èµ–â˜‘ï¸'
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      - name: 'è¿è¡Œç¨‹åºğŸ’»'
        run: python3 ./delete.py
      - name: 'è·å–å½“å‰æ—¥æœŸğŸ•˜'
        id: current_date
        run: |
          echo "date=$(date +"%Y-%m-%d_%H-%M-%S")" >> $GITHUB_OUTPUT
      - name: 'æ£€æŸ¥æ›´æ”¹ğŸ”'
        run: |
          git fetch
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            echo "skip_commit=true" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "skip_commit=false" >> $GITHUB_ENV
          fi
      - name: 'æäº¤datağŸ’¾'
        if: ${{ env.skip_commit == 'false' && github.repository != 'systemannounce/SteamFriends' }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add --all
          git commit -m "${{ steps.current_date.outputs.date }} Delete All non-friends record"

      - name: 'æäº¤ä»£ç ğŸ›«'
        if: ${{ env.skip_commit == 'false' && github.repository != 'systemannounce/SteamFriends' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: 'ä¸Šä¼ ArtifactğŸ’¼'
        if: ${{ github.repository == 'systemannounce/SteamFriends' }}
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: ./README.md
